#pragma once

#include "source2sdk/source2gen/source2gen.hpp"
#include <cstddef>
#include <cstdint>
#include "source2sdk/smartprops/CSmartPropElement.hpp"
#include "source2sdk/smartprops/SmartPropDeformableAttachMode_t.hpp"
#include "source2sdk/smartprops/SmartPropDeformableOrientMode_t.hpp"

// /////////////////////////////////////////////////////////////
// Module: smartprops
// Created using source2gen - github.com/neverlosecc/source2gen
// /////////////////////////////////////////////////////////////

namespace source2sdk
{
    namespace smartprops
    {
        // Registered alignment: unknown
        // Alignment: 0x_
        // Standard-layout class: false
        // Size: 0x_
        // Has VTable
        // Is Abstract
        // Construct allowed
        // 
        // static metadata: MGetKV3ClassDefaults
        // static metadata: MVDataOutlinerAssetNameExpr
        #pragma pack(push, 1)
        class CSmartPropElement_ModelEntity : public source2sdk::smartprops::CSmartPropElement
        {
        public:
            // metadata: MPropertyDescription "Name of the model resource (.vmdl) to place."
            // metadata: MPropertyProvidesEditContextString
            CSmartPropAttributeModelName m_sModelName; // 0x_            
            // metadata: MPropertyFriendlyName "Material Group"
            // metadata: MPropertyDescription "Specifies the name of the material group (skin) to use when displaying the specified model."
            CSmartPropAttributeMaterialGroup m_MaterialGroupName; // 0x_            
            // metadata: MPropertyFriendlyName "Cast Shadows"
            // metadata: MPropertyDescription "Should the entity created by this element cast shadows."
            CSmartPropAttributeBool m_bCastShadows; // 0x_            
            // metadata: MPropertyFriendlyName "Force Static"
            // metadata: MPropertyDescription "Force this model to be placed as a static model rather then generating an entity."
            CSmartPropAttributeBool m_bForceStatic; // 0x_            
            // metadata: MPropertySortPriority "-1"
            // metadata: MPropertySuppressExpr "m_bForceStatic == true"
            // metadata: MPropertyFriendlyName "Attachment Mode"
            // metadata: MPropertyGroupName "Deformable Entity Settings"
            // metadata: MPropertyDescription "If the smart prop is child of a deformable entity, this setting specifies how the entity generated by this element will be attached to the deformable surface."
            source2sdk::smartprops::SmartPropDeformableAttachMode_t m_nDeformableAttachmentMode; // 0x_            
            // metadata: MPropertySortPriority "-1"
            // metadata: MPropertySuppressExpr "m_bForceStatic == true"
            // metadata: MPropertyGroupName "Deformable Entity Settings"
            // metadata: MPropertyDescription "If the smart prop is child of a deformable entity, this setting specifies how the entity generated by this element will be oriented relative to the deformable surface."
            source2sdk::smartprops::SmartPropDeformableOrientMode_t m_nDeformableOrientationMode; // 0x_            
        };
        #pragma pack(pop)
        
        // Cannot assert offsets of fields in CSmartPropElement_ModelEntity because it is not a standard-layout class
        
        static_assert(sizeof(source2sdk::smartprops::CSmartPropElement_ModelEntity) == 0x_);
    };
};
