#pragma once

#include "source2sdk/source2gen/source2gen.hpp"
#include <cstddef>
#include <cstdint>
#include "source2sdk/client/C_PointEntity.hpp"
#include "source2sdk/client/C_SceneEntity_QueuedEvents_t.hpp"
namespace source2sdk
{
    namespace client
    {
        struct C_BaseFlex;
    };
};

// /////////////////////////////////////////////////////////////
// Module: client
// Created using source2gen - github.com/neverlosecc/source2gen
// /////////////////////////////////////////////////////////////

namespace source2sdk
{
    namespace client
    {
        // Registered alignment: 0x_
        // Alignment: 0x_
        // Standard-layout class: false
        // Size: 0x_
        // Has VTable
        // Construct allowed
        // MClassHasEntityLimitedDataDesc
        // 
        // static metadata: MNetworkVarNames "bool m_bIsPlayingBack"
        // static metadata: MNetworkVarNames "bool m_bPaused"
        // static metadata: MNetworkVarNames "bool m_bMultiplayer"
        // static metadata: MNetworkVarNames "bool m_bAutogenerated"
        // static metadata: MNetworkVarNames "float32 m_flForceClientTime"
        // static metadata: MNetworkVarNames "uint16 m_nSceneStringIndex"
        // static metadata: MNetworkVarNames "CHandle< C_BaseFlex > m_hActorList"
        #pragma pack(push, 1)
        class C_SceneEntity : public source2sdk::client::C_PointEntity
        {
        public:
            uint8_t _pad_[0x_]; // 0x_
            // metadata: MNetworkEnable
            bool m_bIsPlayingBack; // 0x_            
            // metadata: MNetworkEnable
            bool m_bPaused; // 0x_            
            // metadata: MNetworkEnable
            bool m_bMultiplayer; // 0x_            
            // metadata: MNetworkEnable
            bool m_bAutogenerated; // 0x_            
            // metadata: MNetworkEnable
            // metadata: MNetworkChangeCallback "OnResetClientTime"
            float m_flForceClientTime; // 0x_            
            // metadata: MNetworkEnable
            // metadata: MNetworkPriority "32"
            std::uint16_t m_nSceneStringIndex; // 0x_            
            bool m_bClientOnly; // 0x_            
            uint8_t _pad_[0x_]; // 0x_
            // m_hOwner has a template type with potentially unknown template parameters. You can try uncommenting the field below.
            // CHandle<source2sdk::client::C_BaseFlex> m_hOwner;
            char m_hOwner[0x_]; // 0x_            
            // metadata: MNetworkEnable
            // metadata: MNetworkPriority "32"
            // m_hActorList has a template type with potentially unknown template parameters. You can try uncommenting the field below.
            // C_NetworkUtlVectorBase<CHandle<source2sdk::client::C_BaseFlex>> m_hActorList;
            char m_hActorList[0x_]; // 0x_            
            bool m_bWasPlaying; // 0x_            
            uint8_t _pad_[0x_]; // 0x_
            // m_QueuedEvents has a template type with potentially unknown template parameters. You can try uncommenting the field below.
            // CUtlVector<source2sdk::client::C_SceneEntity_QueuedEvents_t> m_QueuedEvents;
            char m_QueuedEvents[0x_]; // 0x_            
            float m_flCurrentTime; // 0x_            
            uint8_t _pad_[0x_];
        };
        #pragma pack(pop)
        
        // Cannot assert offsets of fields in C_SceneEntity because it is not a standard-layout class
        
        static_assert(sizeof(source2sdk::client::C_SceneEntity) == 0x_);
    };
};
