#pragma once

#include "source2sdk/source2gen/source2gen.hpp"
#include <cstddef>
#include <cstdint>

// /////////////////////////////////////////////////////////////
// Module: client
// Created using source2gen - github.com/neverlosecc/source2gen
// /////////////////////////////////////////////////////////////

namespace source2sdk
{
    namespace client
    {
        // Enumerator count: 132
        // Alignment: 4
        // Size: 0x_
        enum class EEventPointAuditAction : std::uint32_t
        {
            eEventAudit_GrantMatchPoints = 0x0,
            eEventAudit_RedeemPrize = 0x1,
            eEventAudit_ManualGrant = 0x2,
            eEventAudit_GrantAction_Points = 0x3,
            eEventAudit_GrantOwnership = 0xa,
            eEventAudit_PointItemUsed = 0xb,
            eEventAudit_OfferingPoints = 0xc,
            eEventAudit_CafeLoginReward_DEPRECATED = 0xd,
            eEventAudit_CafeSessionTime_DEPRECATED = 0xe,
            eEventAudit_CafeMatchTimeReward_DEPRECATED = 0xf,
            eEventAudit_CafeMatchPlayed_DEPRECATED = 0x10,
            eEventAudit_Reward = 0x11,
            eEventAudit_SupportGrant = 0x12,
            eEventAudit_CompendiumSelection = 0x13,
            eEventAudit_CompendiumSpectateMatch = 0x14,
            eEventAudit_CompendiumGrant = 0x15,
            eEventAudit_CompendiumDailyWin = 0x16,
            eEventAudit_ChallengeCompleted = 0x17,
            eEventAudit_CharmReward = 0x18,
            eEventAudit_CompendiumUse = 0x19,
            eEventAudit_CompendiumMatch = 0x1a,
            eEventAudit_ChestOpended = 0x1b,
            eEventAudit_ActionItemUsed = 0x1c,
            eEventAudit_WagerCoinsEarned = 0x1d,
            eEventAudit_QuestChallenge = 0x1e,
            eEventAudit_WagerCoinsSpent = 0x1f,
            eEventAudit_WagerXPEarned = 0x20,
            eEventAudit_TipTransfer = 0x21,
            eEventAudit_MysteryItemGranted = 0x22,
            eEventAudit_PlayedMatch = 0x23,
            eEventAudit_WagersSpent = 0x24,
            eEventAudit_WagersGames = 0x25,
            eEventAudit_WagersGamesWon = 0x26,
            eEventAudit_TipGiven = 0x27,
            eEventAudit_Unused1 = 0x28,
            eEventAudit_Unused2 = 0x29,
            eEventAudit_WeekendTourneyPayout = 0x2a,
            eEventAudit_RewardRedeemed = 0x2b,
            eEventAudit_InGamePredictionCorrect = 0x2c,
            eEventAudit_FantasyReward = 0x2d,
            eEventAudit_BracketReward = 0x2e,
            eEventAudit_BattleCupPoints = 0x2f,
            eEventAudit_ClaimAction = 0x30,
            eEventAudit_ClaimActionPointCost = 0x31,
            eEventAudit_ClaimActionPremiumPointCost = 0x32,
            eEventAudit_CustomGameWin = 0x33,
            eEventAudit_EligibleForWeeklyDraw = 0x34,
            eEventAudit_ClaimedWeeklyDraw = 0x35,
            eEventAudit_WeeklyGameResult = 0x36,
            eEventAudit_TriviaPointsEarned = 0x37,
            eEventAudit_CompendiumPrediction = 0x38,
            eEventAudit_CompendiumBracketPrediction = 0x39,
            eEventAudit_ItemGifted = 0x3a,
            eEventAudit_ExploitCorrection = 0x3b,
            eEventAudit_EventGameReward = 0x3c,
            eEventAudit_RewardNotify = 0x3d,
            eEventAudit_EventGameSpend = 0x3e,
            eEventAudit_WonMatchWithPlus = 0x3f,
            eEventAudit_LostMatchWithPlus = 0x40,
            eEventAudit_FirstMatchWithPlus = 0x41,
            eEventAudit_WonMatch = 0x42,
            eEventAudit_RecycleHeroRelic = 0x43,
            eEventAudit_PurchaseHeroRelic = 0x44,
            eEventAudit_PurchaseRandomHeroRelic = 0x45,
            eEventAudit_RevokeOwnership = 0x46,
            eEventAudit_PlusInitialActivation = 0x47,
            eEventAudit_CavernCrawlRoomClaimed = 0x48,
            eEventAudit_TipReceived = 0x49,
            eEventAudit_SuccessfulProPrediction = 0x4a,
            eEventAudit_Mutation = 0x4b,
            eEventAudit_BonusTreasure = 0x4c,
            eEventAudit_ProPrediction = 0x4d,
            eEventAudit_DuplicateRelicRefund = 0x4e,
            eEventAudit_WonMatchDuringEvent = 0x4f,
            eEventAudit_CommendGiven = 0x50,
            eEventAudit_DevGrant = 0x51,
            eEventAudit_InstallDPCApp = 0x52,
            eEventAudit_ItemConsumed = 0x53,
            eEventAudit_DugUpTreasure = 0x54,
            eEventAudit_CoachedMatch = 0x55,
            eEventAudit_CoachTeammateRating = 0x56,
            eEventAudit_AddedPartyFinder = 0x57,
            eEventAudit_AbilityUsed = 0x58,
            eEventAudit_RewardForTreasureOpened = 0x59,
            eEventAudit_AllStarGame = 0x5a,
            eEventAudit_UnderDraft = 0x5b,
            eEventAudit_GuildContract = 0x5c,
            eEventAudit_BountyClaimed = 0x5d,
            eEventAudit_WagerStreakCompleted = 0x5e,
            eEventAudit_SuccessfulBountyIssued = 0x5f,
            eEventAudit_GauntletCompleted = 0x60,
            eEventAudit_CandyGained = 0x61,
            eEventAudit_GuildWeeklyLeaderboard = 0x62,
            eEventAudit_MatchMVP = 0x63,
            eEventAudit_GainedRelicLevels = 0x64,
            eEventAudit_InGameAction = 0x65,
            eEventAudit_ActionListGrant = 0x66,
            eEventAudit_WeeklyQuestReward = 0x67,
            eEventAudit_TwitchDrop = 0x68,
            eEventAudit_SupportersClubTeamWon = 0x69,
            eEventAudit_PlayerCardFullTeams = 0x6a,
            eEventAudit_ContestVote = 0x6b,
            eEventAudit_CompendiumPredictionSet = 0x6c,
            eEventAudit_BlessingPurchase = 0x6d,
            eEventAudit_MysteryBoxReward = 0x6e,
            eEventAudit_PurchaseAvoidPlayerSlot = 0x6f,
            eEventAudit_FeaturedGamemodePlayed = 0x70,
            eEventAudit_BattleReport = 0x71,
            eEventAudit_StickerTeamPageCompletion = 0x72,
            eEventAudit_StickerPlaced = 0x73,
            eEventAudit_LostMatch = 0x74,
            eEventAudit_CandyShopPurchase = 0x75,
            eEventAudit_FantasyCraftingMats = 0x76,
            eEventAudit_FantasyClaimReward = 0x77,
            eEventAudit_OverworldNodeReward = 0x78,
            eEventAudit_OverworldEncounterReward = 0x79,
            eEventAudit_OverworldNodeUnlocked = 0x7a,
            eEventAudit_CraftworksPurchase = 0x7b,
            eEventAudit_MonsterHunterCraft = 0x7c,
            eEventAudit_MonsterHunterRankReward = 0x7e,
            eEventAudit_MonsterHunterCodexReward = 0x7f,
            eEventAudit_MonsterHunterCraftSet = 0x80,
            eEventAudit_CompanionPrediction = 0x7d,
            eEventAudit_EventRankingReward = 0x81,
            eEventAudit_ConvertPoints = 0x82,
            eEventAudit_MonsterHunterAutoCraft = 0x83,
            eEventAudit_QuarteroAntiqueCashIn = 0x84,
            eEventAudit_OverworldFortuneReward = 0x85,
            eEventAudit_OverworldFortuneRequest = 0x86,
            eEventAudit_OverworldFortunePermanentReward = 0x87,
            eEventAudit_OverworldFortuneTellerStoryNodeReward = 0x88,
            eEventAudit_Count = 0x89,
        };
    };
};
