#pragma once
#include <cstdint>

// /////////////////////////////////////////////////////////////
// Module: client
// Created using source2gen - github.com/neverlosecc/source2gen
// /////////////////////////////////////////////////////////////

namespace source2sdk::client
{
    // Enumerator count: 65
    // Alignment: 4
    // Size: 0x4
    enum class modifierstate : std::uint32_t
    {
        MODIFIER_STATE_ROOTED = 0x0,
        MODIFIER_STATE_DISARMED = 0x1,
        MODIFIER_STATE_ATTACK_IMMUNE = 0x2,
        MODIFIER_STATE_SILENCED = 0x3,
        MODIFIER_STATE_MUTED = 0x4,
        MODIFIER_STATE_STUNNED = 0x5,
        MODIFIER_STATE_HEXED = 0x6,
        MODIFIER_STATE_INVISIBLE = 0x7,
        MODIFIER_STATE_INVULNERABLE = 0x8,
        MODIFIER_STATE_MAGIC_IMMUNE = 0x9,
        MODIFIER_STATE_PROVIDES_VISION = 0xa,
        MODIFIER_STATE_NIGHTMARED = 0xb,
        MODIFIER_STATE_BLOCK_DISABLED = 0xc,
        MODIFIER_STATE_EVADE_DISABLED = 0xd,
        MODIFIER_STATE_UNSELECTABLE = 0xe,
        MODIFIER_STATE_CANNOT_TARGET_ENEMIES = 0xf,
        MODIFIER_STATE_CANNOT_TARGET_BUILDINGS = 0x10,
        MODIFIER_STATE_CANNOT_MISS = 0x11,
        MODIFIER_STATE_SPECIALLY_DENIABLE = 0x12,
        MODIFIER_STATE_FROZEN = 0x13,
        MODIFIER_STATE_COMMAND_RESTRICTED = 0x14,
        MODIFIER_STATE_NOT_ON_MINIMAP = 0x15,
        MODIFIER_STATE_LOW_ATTACK_PRIORITY = 0x16,
        MODIFIER_STATE_NO_HEALTH_BAR = 0x17,
        MODIFIER_STATE_NO_HEALTH_BAR_FOR_ENEMIES = 0x18,
        MODIFIER_STATE_NO_HEALTH_BAR_FOR_OTHER_PLAYERS = 0x19,
        MODIFIER_STATE_FLYING = 0x1a,
        MODIFIER_STATE_NO_UNIT_COLLISION = 0x1b,
        MODIFIER_STATE_NO_TEAM_MOVE_TO = 0x1c,
        MODIFIER_STATE_NO_TEAM_SELECT = 0x1d,
        MODIFIER_STATE_PASSIVES_DISABLED = 0x1e,
        MODIFIER_STATE_DOMINATED = 0x1f,
        MODIFIER_STATE_BLIND = 0x20,
        MODIFIER_STATE_OUT_OF_GAME = 0x21,
        MODIFIER_STATE_FAKE_ALLY = 0x22,
        MODIFIER_STATE_FLYING_FOR_PATHING_PURPOSES_ONLY = 0x23,
        MODIFIER_STATE_TRUESIGHT_IMMUNE = 0x24,
        MODIFIER_STATE_UNTARGETABLE = 0x25,
        MODIFIER_STATE_UNTARGETABLE_ALLIED = 0x26,
        MODIFIER_STATE_UNTARGETABLE_ENEMY = 0x27,
        MODIFIER_STATE_UNTARGETABLE_SELF = 0x28,
        MODIFIER_STATE_IGNORING_MOVE_AND_ATTACK_ORDERS = 0x29,
        MODIFIER_STATE_ALLOW_PATHING_THROUGH_TREES = 0x2a,
        MODIFIER_STATE_NOT_ON_MINIMAP_FOR_ENEMIES = 0x2b,
        MODIFIER_STATE_UNSLOWABLE = 0x2c,
        MODIFIER_STATE_TETHERED = 0x2d,
        MODIFIER_STATE_IGNORING_STOP_ORDERS = 0x2e,
        MODIFIER_STATE_FEARED = 0x2f,
        MODIFIER_STATE_TAUNTED = 0x30,
        MODIFIER_STATE_CANNOT_BE_MOTION_CONTROLLED = 0x31,
        MODIFIER_STATE_FORCED_FLYING_VISION = 0x32,
        MODIFIER_STATE_ATTACK_ALLIES = 0x33,
        MODIFIER_STATE_ALLOW_PATHING_THROUGH_CLIFFS = 0x34,
        MODIFIER_STATE_ALLOW_PATHING_THROUGH_FISSURE = 0x35,
        MODIFIER_STATE_SPECIALLY_UNDENIABLE = 0x36,
        MODIFIER_STATE_ALLOW_PATHING_THROUGH_OBSTRUCTIONS = 0x37,
        MODIFIER_STATE_DEBUFF_IMMUNE = 0x38,
        MODIFIER_STATE_NO_INVISIBILITY_VISUALS = 0x39,
        MODIFIER_STATE_ALLOW_PATHING_THROUGH_BASE_BLOCKER = 0x3a,
        MODIFIER_STATE_IGNORING_MOVE_ORDERS = 0x3b,
        MODIFIER_STATE_ATTACKS_ARE_MELEE = 0x3c,
        MODIFIER_STATE_CAN_USE_BACKPACK_ITEMS = 0x3d,
        MODIFIER_STATE_CASTS_IGNORE_CHANNELING = 0x3e,
        MODIFIER_STATE_ATTACKS_DONT_REVEAL = 0x3f,
        MODIFIER_STATE_LAST = 0x40,
    };
};
