#pragma once
#include <cstdint>

// /////////////////////////////////////////////////////////////
// Module: client
// Created using source2gen - github.com/neverlosecc/source2gen
// /////////////////////////////////////////////////////////////

namespace source2sdk::client
{
    // Enumerator count: 36
    // Alignment: 4
    // Size: 0x4
    enum class PARTICLE_MESSAGE : std::uint32_t
    {
        GAME_PARTICLE_MANAGER_EVENT_CREATE = 0x0,
        GAME_PARTICLE_MANAGER_EVENT_UPDATE = 0x1,
        GAME_PARTICLE_MANAGER_EVENT_UPDATE_FORWARD = 0x2,
        GAME_PARTICLE_MANAGER_EVENT_UPDATE_ORIENTATION = 0x3,
        GAME_PARTICLE_MANAGER_EVENT_UPDATE_FALLBACK = 0x4,
        GAME_PARTICLE_MANAGER_EVENT_UPDATE_ENT = 0x5,
        GAME_PARTICLE_MANAGER_EVENT_UPDATE_OFFSET = 0x6,
        GAME_PARTICLE_MANAGER_EVENT_DESTROY = 0x7,
        GAME_PARTICLE_MANAGER_EVENT_DESTROY_INVOLVING = 0x8,
        GAME_PARTICLE_MANAGER_EVENT_RELEASE = 0x9,
        GAME_PARTICLE_MANAGER_EVENT_LATENCY = 0xa,
        GAME_PARTICLE_MANAGER_EVENT_SHOULD_DRAW = 0xb,
        GAME_PARTICLE_MANAGER_EVENT_FROZEN = 0xc,
        GAME_PARTICLE_MANAGER_EVENT_CHANGE_CONTROL_POINT_ATTACHMENT = 0xd,
        GAME_PARTICLE_MANAGER_EVENT_UPDATE_ENTITY_POSITION = 0xe,
        GAME_PARTICLE_MANAGER_EVENT_SET_FOW_PROPERTIES = 0xf,
        GAME_PARTICLE_MANAGER_EVENT_SET_TEXT = 0x10,
        GAME_PARTICLE_MANAGER_EVENT_SET_SHOULD_CHECK_FOW = 0x11,
        GAME_PARTICLE_MANAGER_EVENT_SET_CONTROL_POINT_MODEL = 0x12,
        GAME_PARTICLE_MANAGER_EVENT_SET_CONTROL_POINT_SNAPSHOT = 0x13,
        GAME_PARTICLE_MANAGER_EVENT_SET_TEXTURE_ATTRIBUTE = 0x14,
        GAME_PARTICLE_MANAGER_EVENT_SET_SCENE_OBJECT_GENERIC_FLAG = 0x15,
        GAME_PARTICLE_MANAGER_EVENT_SET_SCENE_OBJECT_TINT_AND_DESAT = 0x16,
        GAME_PARTICLE_MANAGER_EVENT_DESTROY_NAMED = 0x17,
        GAME_PARTICLE_MANAGER_EVENT_SKIP_TO_TIME = 0x18,
        GAME_PARTICLE_MANAGER_EVENT_CAN_FREEZE = 0x19,
        GAME_PARTICLE_MANAGER_EVENT_SET_NAMED_VALUE_CONTEXT = 0x1a,
        GAME_PARTICLE_MANAGER_EVENT_UPDATE_TRANSFORM = 0x1b,
        GAME_PARTICLE_MANAGER_EVENT_FREEZE_TRANSITION_OVERRIDE = 0x1c,
        GAME_PARTICLE_MANAGER_EVENT_FREEZE_INVOLVING = 0x1d,
        GAME_PARTICLE_MANAGER_EVENT_ADD_MODELLIST_OVERRIDE_ELEMENT = 0x1e,
        GAME_PARTICLE_MANAGER_EVENT_CLEAR_MODELLIST_OVERRIDE = 0x1f,
        GAME_PARTICLE_MANAGER_EVENT_CREATE_PHYSICS_SIM = 0x20,
        GAME_PARTICLE_MANAGER_EVENT_DESTROY_PHYSICS_SIM = 0x21,
        GAME_PARTICLE_MANAGER_EVENT_SET_VDATA = 0x22,
        GAME_PARTICLE_MANAGER_EVENT_SET_MATERIAL_OVERRIDE = 0x23,
    };
};
