#pragma once

#include "source2sdk/source2gen/source2gen.hpp"
#include <cstddef>
#include <cstdint>

// /////////////////////////////////////////////////////////////
// Module: pulse_runtime_lib
// Created using source2gen - github.com/neverlosecc/source2gen
// /////////////////////////////////////////////////////////////

namespace source2sdk
{
    namespace pulse_runtime_lib
    {
        // Enumerator count: 125
        // Alignment: 2
        // Size: 0x_
        enum class PulseInstructionCode_t : std::uint16_t
        {
            INVALID = 0x0,
            IMMEDIATE_HALT = 0x1,
            RETURN_VOID = 0x2,
            RETURN_VALUE = 0x3,
            NOP = 0x4,
            JUMP = 0x5,
            JUMP_COND = 0x6,
            CHUNK_LEAP = 0x7,
            CHUNK_LEAP_COND = 0x8,
            PULSE_CALL_SYNC = 0x9,
            PULSE_CALL_ASYNC_FIRE = 0xa,
            CELL_INVOKE = 0xb,
            LIBRARY_INVOKE = 0xc,
            SET_VAR = 0xd,
            GET_VAR = 0xe,
            GET_VAR_DETACH = 0xf,
            DETACH_REGISTER = 0x10,
            SET_VAR_ARRAY_ELEMENT_1D = 0x11,
            SET_VAR_OBSERVABLE = 0x12,
            GET_CONST = 0x13,
            GET_ARRAY_ELEMENT = 0x14,
            GET_DOMAIN_VALUE = 0x15,
            COPY = 0x16,
            NOT = 0x17,
            NEGATE = 0x18,
            ADD = 0x19,
            SUB = 0x1a,
            MUL = 0x1b,
            DIV = 0x1c,
            MOD = 0x1d,
            LT = 0x1e,
            LTE = 0x1f,
            EQ = 0x20,
            NE = 0x21,
            AND = 0x22,
            OR = 0x23,
            SCALE = 0x24,
            SCALE_INV = 0x25,
            ELEMENT_ACCESS = 0x26,
            CONVERT_VALUE = 0x27,
            REINTERPRET_INSTANCE = 0x28,
            GET_BLACKBOARD_REFERENCE = 0x29,
            SET_BLACKBOARD_REFERENCE = 0x2a,
            LAST_SERIALIZED_CODE = 0x2b,
            NEGATE_INT = 0x2c,
            NEGATE_FLOAT = 0x2d,
            NEGATE_VEC2 = 0x2e,
            NEGATE_VEC3 = 0x2f,
            NEGATE_VEC4 = 0x30,
            ADD_INT = 0x31,
            ADD_FLOAT = 0x32,
            ADD_STRING = 0x33,
            ADD_VEC2 = 0x34,
            ADD_VEC3 = 0x35,
            ADD_VEC3WS_VEC3 = 0x36,
            ADD_VEC3_VEC3WS = 0x37,
            ADD_VEC4 = 0x38,
            ADD_GAMETIME_FLOAT = 0x39,
            ADD_FLOAT_GAMETIME = 0x3a,
            SUB_INT = 0x3b,
            SUB_FLOAT = 0x3c,
            SUB_VEC2 = 0x3d,
            SUB_VEC3 = 0x3e,
            SUB_VEC3WS_VEC3 = 0x3f,
            SUB_VEC3WS_VEC3WS = 0x40,
            SUB_VEC4 = 0x41,
            SUB_GAMETIME_FLOAT = 0x42,
            SUB_GAMETIME = 0x43,
            MUL_INT = 0x44,
            MUL_FLOAT = 0x45,
            DIV_FLOAT = 0x46,
            MOD_INT = 0x47,
            MOD_FLOAT = 0x48,
            LT_INT = 0x49,
            LT_FLOAT = 0x4a,
            LT_GAMETIME = 0x4b,
            LTE_INT = 0x4c,
            LTE_FLOAT = 0x4d,
            LTE_GAMETIME = 0x4e,
            EQ_BOOL = 0x4f,
            EQ_INT = 0x50,
            EQ_FLOAT = 0x51,
            EQ_VEC2 = 0x52,
            EQ_VEC3 = 0x53,
            EQ_VEC3WS = 0x54,
            EQ_VEC4 = 0x55,
            EQ_STRING = 0x56,
            EQ_ENTITY_NAME = 0x57,
            EQ_SCHEMA_ENUM = 0x58,
            EQ_EHANDLE = 0x59,
            EQ_PANEL_HANDLE = 0x5a,
            EQ_OPAQUE_HANDLE = 0x5b,
            EQ_TEST_HANDLE = 0x5c,
            EQ_COLOR_RGB = 0x5d,
            EQ_ARRAY = 0x5e,
            EQ_GAMETIME = 0x5f,
            NE_BOOL = 0x60,
            NE_INT = 0x61,
            NE_FLOAT = 0x62,
            NE_VEC2 = 0x63,
            NE_VEC3 = 0x64,
            NE_VEC3WS = 0x65,
            NE_VEC4 = 0x66,
            NE_STRING = 0x67,
            NE_ENTITY_NAME = 0x68,
            NE_SCHEMA_ENUM = 0x69,
            NE_EHANDLE = 0x6a,
            NE_PANEL_HANDLE = 0x6b,
            NE_OPAQUE_HANDLE = 0x6c,
            NE_TEST_HANDLE = 0x6d,
            NE_COLOR_RGB = 0x6e,
            NE_ARRAY = 0x6f,
            NE_GAMETIME = 0x70,
            SCALE_VEC3 = 0x71,
            SCALE_VEC2 = 0x72,
            SCALE_VEC4 = 0x73,
            SCALE_INV_VEC3 = 0x74,
            SCALE_INV_VEC2 = 0x75,
            SCALE_INV_VEC4 = 0x76,
            ELEMENT_ACCESS_VEC2 = 0x77,
            ELEMENT_ACCESS_VEC3 = 0x78,
            ELEMENT_ACCESS_VEC3WS = 0x79,
            ELEMENT_ACCESS_VEC4 = 0x7a,
            ELEMENT_ACCESS_COLOR_RGB = 0x7b,
            GET_CONST_INLINE_STORAGE = 0x7c,
        };
    };
};
